version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-sql
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  task:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=example
